name: Build and Deploy .exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    outputs:
      zip-path: ${{ steps.zip.outputs.zip-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.300'

      - name: Restore dependencies
        run: dotnet restore camouelleon/camouelleon.sln

      - name: Build and publish application
        run: dotnet publish camouelleon/camouelleon.sln -c Release -r win-x64 --self-contained -o ./publish

      - name: Create ZIP archive
        id: zip
        run: |
          powershell Compress-Archive -Path ./publish/* -DestinationPath camouelleon.zip
          echo "zip-path=camouelleon.zip" >> $env:GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: camouelleon-zip
          path: camouelleon.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: camouelleon-zip

      - name: Upload ZIP to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "camouelleon.zip"
          target: "/var/www/telechargement/"
