name: Build and Deploy .exe

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.300'

      - name: Restore dependencies
        run: dotnet restore camouelleon/camouelleon.sln

      - name: Build and publish application
        run: dotnet publish camouelleon/camouelleon.sln -c Release -r win-x64 --self-contained -o ./publish

      - name: Create ZIP archive
        run: powershell Compress-Archive -Path ./publish/* -DestinationPath camouelleon.zip

      - name: Install WinSCP with Chocolatey
        run: choco install winscp -y

      - name: Upload ZIP via SCP with WinSCP
        run: |
          echo "$env:PRIVATE_KEY" > key.ppk
          "C:\Program Files (x86)\WinSCP\WinSCP.com" /log=log.txt /command `
            "open scp://${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}/ -privatekey=key.ppk -hostkey=* -rawsettings Compression=1" `
            "put camouelleon.zip /var/www/telechargement/" `
            "exit"
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
